[project]
name = "test-uv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests==2.31.0",
]
git config --global user.email "you@example.com"
  git config --global user.name "Your Name"